default_active_agent="idog"
[[llms]]
name = "gpt-4.1-mini"
provider = "openai"
[[llms]]
name = "gpt-4.1"
provider = "openai"
[[mcp_servers]]
name = "idog"
host = "127.0.0.1"
port = "8889"
routable_nodes= ["bioka"]
[[mcp_servers]]
name = "bioka"
host = "127.0.0.1"
port = "8888"
routable_nodes= []
