name: Docker Image CI - Frontend (Development)

on:
  push:
    branches: [ "development" ] # 触发分支改为 development
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ "development" ] # PR 目标分支改为 development
    paths:
      - 'frontend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository}}-frontend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 从 Git 分支名提取 Docker 元数据 (标签)
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr

      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun quasar build

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          # 仅在 push 事件时推送 (非 PR)
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
